// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demo.Data;

#nullable disable

namespace demo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("demo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1964, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            HireDate = new DateTime(1995, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "1234 Executive Way, Los Angeles, CA 90210",
                            LastName = "Heart",
                            Notes = "Company founder and visionary leader with over 25 years of experience",
                            Position = "CEO",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1981, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            HireDate = new DateTime(2012, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "567 Sunset Boulevard, San Francisco, CA 94102",
                            LastName = "Peyton",
                            Notes = "Dedicated sales professional with excellent customer service skills",
                            Position = "Sales Assistant",
                            State = "California",
                            Title = "Mrs."
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1974, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            HireDate = new DateTime(2002, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "890 Marketing Drive, Little Rock, AR 72201",
                            LastName = "Reagan",
                            Notes = "Strategic marketing leader specializing in digital transformation",
                            Position = "CMO",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1977, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Greta",
                            HireDate = new DateTime(1998, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "123 Peachtree Street, Atlanta, GA 30309",
                            LastName = "Sims",
                            Notes = "Experienced HR professional focused on employee development and retention",
                            Position = "HR Manager",
                            State = "Georgia",
                            Title = "Ms."
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1968, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brett",
                            HireDate = new DateTime(2009, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "456 Technology Lane, Boise, ID 83702",
                            LastName = "Wade",
                            Notes = "Technology infrastructure specialist with expertise in cloud solutions",
                            Position = "IT Manager",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1974, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sandra",
                            HireDate = new DateTime(2005, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "789 Financial Way, Salt Lake City, UT 84101",
                            LastName = "Johnson",
                            Notes = "Financial control expert with CPA certification and audit experience",
                            Position = "Controller",
                            State = "Utah",
                            Title = "Mrs."
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1978, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            HireDate = new DateTime(2009, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "321 Shipping Street, San Diego, CA 92101",
                            LastName = "Carter",
                            Notes = "Logistics coordination specialist with supply chain optimization skills",
                            Position = "Shipping Manager",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1985, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cynthia",
                            HireDate = new DateTime(2008, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "654 Human Resources Blvd, Fayetteville, AR 72703",
                            LastName = "Stanwick",
                            Notes = "Detail-oriented HR support specialist with recruitment expertise",
                            Position = "HR Assistant",
                            State = "Arkansas",
                            Title = "Ms."
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1972, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kent",
                            HireDate = new DateTime(2009, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "987 Mediation Avenue, Kansas City, MO 64108",
                            LastName = "Samuelson",
                            Notes = "PhD in Organizational Psychology, employee relations specialist",
                            Position = "Ombudsman",
                            State = "Missouri",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1982, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Taylor",
                            HireDate = new DateTime(2012, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "147 Network Drive, Sacramento, CA 95814",
                            LastName = "Riley",
                            Notes = "Network infrastructure specialist with cybersecurity certifications",
                            Position = "Network Admin",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1984, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sam",
                            HireDate = new DateTime(2012, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "258 Sales Circle, Savannah, GA 31401",
                            LastName = "Hill",
                            Notes = "Customer relationship specialist with strong communication skills",
                            Position = "Sales Assistant",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1988, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kelly",
                            HireDate = new DateTime(2012, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "369 Support Street, Fresno, CA 93701",
                            LastName = "Rodriguez",
                            Notes = "Technical support specialist with multilingual customer service skills",
                            Position = "Support Assistant",
                            State = "California",
                            Title = "Ms."
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1977, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            HireDate = new DateTime(2008, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "741 Training Boulevard, Las Vegas, NV 89101",
                            LastName = "Maguire",
                            Notes = "Corporate training specialist with adult education certification",
                            Position = "Trainer",
                            State = "Nevada",
                            Title = "Mrs."
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1984, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Walter",
                            HireDate = new DateTime(2011, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeAddress = "852 Developer Lane, Meridian, ID 83642",
                            LastName = "Hobbs",
                            Notes = "Full-stack developer with expertise in modern web technologies",
                            Position = "Programmer",
                            State = "Idaho",
                            Title = "Mr."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
